sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
- sudo apt-get install xzdec && tlmgr init-usertree && tlmgr install xkeyval
- tlmgr install xcolor
script:
- sudo pdflatex -interaction=nonstopmode -halt-on-error Syllabus-EPL1203.tex
